image: Visual Studio 2017
before_build:
  - choco install gitversion
build_script:
  - ps: .\MVS.Template.ps1 install
deploy:
  provider: NuGet
  api_key: 
    secure: ROObH96V4PKca6fhWnjQ/LMahI+KCgR5j6O9nwq1wxS3i8qb5u25sVK+cdiqNjWH 
  skip_symbols: false
  artifact: /.*\.nupkg/
  verbosity: detailed